# Global Settings
# Publish is directory to publish relative to root
# Command is build command
# Base is directory to change to before building - that's where it'll look for package.json
#
 [build]
#  base = "public/"
#  publish = "public"
#  command = "gatsby build"
#
# Production context:
# All deploys to main repository branch
#
# [context.production]
#  command = "gatsby build"
#  [context.production.environment]
#    ACCESS_TOKEN = "super secret"
#
# Deploy Preview Context:
# All Deploy Previews inherit these Settings
#
# [context.deploy-preview.environment]
#  ACCESS_TOKEN = "not so secret"
#
# Branch Deploy Context: 
# All deploys not in active preview will inherit
#
# [context.branch-deploy]
#  command = "make staging"
#
# Specific Branch Context: 
# Deploys from this branch override current
#
# [context.feature]
#  command = "make feature"
# [context."features/branch"]
#  command = "gulp" 